version: "3"
services:
  postgres:
    container_name: calendar
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - "TZ=Asia/Tokyo"
      - "POSTGRES_DB=calendar"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_INITDB_ARGS=--encoding=UTF-8"
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - ../src/main/resources/:/tmp
